mcoc/__init__.py
import os
from mcoc import views
from decouple import config
from flask import Flask


def create_app():
    app = Flask(__name__)
    app.config['DATABASE'] = config("DATABASE_URL")
    app.register_blueprint(views.bp)

    return app

mcoc/views.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from datetime import datetime
from mcoc.database import add_champion, add_account, remove_champion, remove_account, get_champion

bp = Blueprint('view', __name__, url_prefix='/')

@bp.route("", methods=('GET','POST'))
def home_page():
    day_name = datetime.today().strftime("&A")
    remove_champion(1)
    remove_account("umturock")
    return render_template("home.html", day = day_name)


@bp.route("champs")
def champs_page():
    add_account("umturock","accpsswrd", "accmail", "uncollected", 60)
    add_champion("hulk", 5, 55, 5, 100, "umturock")
    champ = get_champion(1, None, None, None)
    return render_template("champs.html", champ=champ)

mcoc/templates/champs.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My movies - Movie list</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general.css') }}"/>
  </head>
  <body>
    <h1>Movies</h1>
    <table class="table is-narrow is-striped is-hoverable" width="100%">
      <thead>
          <tr>
              <th> ID</th>
              <th>Name</th>
              <th>Rank</th>
              <th>Level</th>
              <th>Star</th>
              <th>Signature level</th>
              <th>Account</th>
              <th></th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>{{ champ[0][0] }}</td>
              <td>{{ champ[0][1] }}</td>
              <td>{{ champ[0][2] }}</td>
              <td>{{ champ[0][3] }}</td>
              <td>{{ champ[0][4] }}</td>
              <td>{{ champ[0][5] }}</td>
              <td>{{ champ[0][6] }}</td>

          </tr>
      </tbody> 
  </table>
  </body>
</html>

mcoc/templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>My movie collection</h1>
    <p>Have a nice {{ day }}!</p>

    <ul>
      <li><a href="{{ url_for('view.champs_page') }}">List movies</a></li>
    </ul>
{% endblock %}

mcoc/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My movies - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='general.css') }}"/>
  </head>
  <body>
    <header>
        <nav>
          <ul>
            <li><a href="{{ url_for('view.home_page') }}">Home</a></li>
            <li><a href="{{ url_for('view.champs_page') }}">List movies</a></li>
          </ul>
        </nav>
    </header>
    {% block body %}{% endblock %}
  </body>
</html>

templates/home.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>My movie collection</h1>
    <p>Have a nice {{ day }}!</p>

    <ul>
      <li><a href="{{ url_for('movies_page') }}">List movies</a></li>
    </ul>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My movies - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='mymovies.css') }}"/>
  </head>
  <body>
    <header>
        <nav>
          <ul>
            <li><a href="{{ url_for('home_page') }}">Home</a></li>
            <li><a href="{{ url_for('movies_page') }}">List movies</a></li>
          </ul>
        </nav>
    </header>
    {% block body %}{% endblock %}
  </body>
</html>

templates/movies.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>My movies - Movie list</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='mymovies.css') }}"/>
  </head>
  <body>
    <h1>Movies</h1>
  </body>
</html>